[
    "as a",
    "high school student",
    "middle school student",
    "preparing for",
    "exams",
    "was born from",
    "personal frustration",
    "makes it unique",
    "and eventually",
    "the intention",
    "it’s been a journey",
    "it's been a journey",
    "a journey",
    "it’s all about",
    "it's all about",
    "leverage that knowledge",
    "dive into",
    "become a versatile programmer",
    "my adventure",
    "foundational principles",
    "how computers truly work",
    "the world of data",
    "an ambitious goal",
    "excited to build",
    "programming toolkit",
    "summer of learning",
    "something insane",
    "think of it like",
    "drowning in",
    "last week",
    "next week",
]
