[ 
    "more than just",
    "it isn’t a ",
    "it isn't a ",
    "this isn’t a ",
    "this isn't a ",
    "isn’t just a",
    "isn't just a",
    "it’s not just",
    "it's not just",
    "i'm not just",
    "i’m not just",
    "it’s just not",
    "it's just not",
    "i'm just not",
    "i’m just not",
    "isn’t just",
    "isn't just",
    "didn't just",
    "didn’t just",
    "more than a",
    "it’s more",
    "it's more",
]
